### ISSUE TITLE
fake/phantom lobby show up while not exist actually

### ISSUE THREAD

**Issue by 777CEMAK** [sc2-arcade-watcher/issue-tracker#12]
timezone CEST
![report phantom lobby](https://github.com/sc2-arcade-watcher/issue-tracker/assets/125599579/fa228f27-f41a-44da-8434-3c946714ab3d)

**Comment by Talv** [comment]
Fixed.

![image](https://github.com/sc2-arcade-watcher/issue-tracker/assets/6976458/5b2d50bd-ce78-44e1-8f42-0dfd81fceeca)
