### ISSUE TITLE
sc2 arcade not showing any open lobbies

### ISSUE THREAD

**Issue by develown** [sc2-arcade-watcher/issue-tracker#13]
sc2 arcade not showing any open lobbies

as in title
![sc2](https://github.com/user-attachments/assets/8280a406-42dc-4d43-98bb-e0633aa11140)

**Comment by Talv** [comment]
Thanks for the report using proper channels, although I'm aware by this point.

It's due to complications surrounding the recent SC2 patch. I'll try to get it sorted out before end of this week, sorry.

**Comment by Talv** [comment]
It's done. Sorry for this huge delay.
