### ISSUE TITLE
Web API: profile search by regionId and profileGameId

### ISSUE THREAD

**Issue by nephest** [sc2-arcade-watcher/issue-tracker#9]
Is it possible to add a new `Profiles` endpoint that will search by `regionId` and `profileGameId` combination? Something like `/profiles/{regionId}/{profileGameId}`. I'd like to use it in my ladder tracker([sc2pulse](https://sc2pulse.nephest.com/sc2/?#stats)), and I'm sure other trackers and projects like [sc2revealed](https://sc2revealed.com/) would benefit from a search like this.

**Comment by Talv** [comment]
Hey there.
Yeah I'm familiar with your website, nice work! (Even though SC2 ladder isn't my thing).

Anyway, sure, I'll add this. Along with some docs - describing in which situations this identifier might be not available / not indexed.

I'll do so next weekend, most likely.

**Comment by nephest** [comment]
Excellent! I understand that not all players are indexed, but even a limited search is a nice tool to have IMO. It's a fairly unique source of information, just like your entire project is.

**Comment by Talv** [comment]
It's done: https://api.sc2arcade.com/docs/api/index.html#/Profiles/get_profiles__regionId___profileGameId_
